version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
    - SECRET_KEY=django-insecure-6wu_rgog#4#jz0%-wfi%v%wknn9!#)n8die&s8kdcq(54@5-)n
    - DEBUG=1
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
  
volumes:
  postgres_data:
