# Generated by Django 4.1 on 2022-08-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('count', models.PositiveSmallIntegerField(verbose_name='COUNT')),
            ],
            options={
                'verbose_name': 'CATEGORY',
                'verbose_name_plural': 'CATEGORYs',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='items', verbose_name='IMG')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desk', models.TextField(verbose_name='Desk')),
                ('cost', models.PositiveIntegerField(verbose_name='Price')),
                ('count', models.PositiveSmallIntegerField(verbose_name='COUNT')),
            ],
            options={
                'verbose_name': 'ITEM',
                'verbose_name_plural': 'ITEMs',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategorys',
            },
        ),
    ]
