# Generated by Django 4.1 on 2022-08-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='basket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.basket', verbose_name='BASKET'),
        ),
        migrations.AddField(
            model_name='item',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.category', verbose_name='Category'),
        ),
    ]
